relationTypeListAut = {'500': 'RelationToPerName', 
                       '510': 'RelationToCorpName', 
                       '511': 'RelationToMeetName', 
                       '530': 'RelationToUniTitle',
                       '548': 'RelationToChronTerm', 
                       '550': 'RelationToTopicTerm', 
                       '551': 'RelationToGeoName'}

relationTypeListBib = {'100': 'RelationToPerName', 
                       '110': 'RelationToCorpName', 
                       '111': 'RelationToMeetName', 
                       '130': 'RelationToUniTitle',
                       '600': ['RelationToPerName', 'SubjectAddedEntry'],
                       '610': ['RelationToCorpName', 'SubjectAddedEntry'],
                       '611': ['RelationToMeetName', 'SubjectAddedEntry'],
                       '630': ['RelationToUniTitle', 'SubjectAddedEntry'],
                       '650': ['RelationToTopicTerm', 'SubjectAddedEntry'],
                       '651': ['RelationToGeoName', 'SubjectAddedEntry'],
                       '655': ['RelationToTopicTerm', 'GenreOrForm'],
                       '700': 'RelationToPerName', 
                       '710': 'RelationToCorpName', 
                       '711': 'RelationToMeetName', 
                       '730': 'RelationToUniTitle',
                       '751': 'RelationToGeoName',
                       '770': ['RelationToResource', 'SupplementToMainTitle'],
                       '772': ['RelationToResource', 'MainTitleToSupplement'],
                       '775': ['RelationToResource', 'LangVariant'],
                       '776': ['RelationToResource', 'ManifestLevel'],
                       '780': ['RelationToResource', 'Predecessor'],
                       '785': ['RelationToResource', 'Successor']}

entityGenCodes = ['b', 'f', 'g', 'n', 'p', 's', 'u']

entitySpecCodes = ["gib",
                   "gif",
                   "gik",
                   "gil",
                   "gin",
                   "gio",
                   "gir",
                   "giv",
                   "giw",
                   "gix",
                   "giz",
                   "gxz",
                   "kif",
                   "kim",
                   "kio",
                   "kip",
                   "kiv",
                   "kir",
                   "kiz",
                   "kxz",
                   "pif",
                   "pik",
                   "pip",
                   "pis",
                   "piz",
                   "pxg",
                   "pxl",
                   "pxs",
                   "sab",
                   "sad",
                   "saf",
                   "sag",
                   "sam",
                   "saz",
                   "sie",
                   "sif",
                   "sih",
                   "sip",
                   "sis",
                   "siu",
                   "siw",
                   "siz",
                   "slz",
                   "snz",
                   "sxz",
                   "szz",
                   "uiz",
                   "vie",
                   "vif",
                   "wid",
                   "wie",
                   "wif",
                   "wim",
                   "win",
                   "wip",
                   "wis",
                   "wit"]

relationGndTypeList = {'Work',
                       'biographicalOrHistoricalInformation',
                       'narrowerTermGeneric',
                       'broaderTerm',
                       'choreographer',
                       'designer',
                       'temporaryNameOfTheCorporateBody',
                       'memberOfTheFamily',
                       'composer',
                       'typeOfCoordinates',
                       'owner',
                       'preferredNameEntityForThePerson',
                       'arranger',
                       'hierarchicalSuperiorOfPlaceOrGeographicName',
                       'place',
                       'accreditedAuthor',
                       'addressee',
                       'definition',
                       'gndSubjectCategory',
                       'precedingSubject',
                       'precedingWork',
                       'superPropertyOf',
                       'sponsorOrPatron',
                       'placeOfManufacture',
                       'MusicalCorporateBody',
                       'relatedConferenceOrEvent',
                       'acquaintanceshipOrFriendship',
                       'preferredNameForTheFamily',
                       'SoftwareProduct',
                       'architect',
                       'preferredNameForThePlaceOrGeographicName',
                       'coordinates',
                       'broaderTermWithMoreThanOneElement',
                       'relatedFamily',
                       'SubjectHeadingSensoStricto',
                       'placeOfBirthAsLiteral',
                       'broderTermGeneral',
                       'relatedDdcWithDegreeOfDeterminacy2',
                       'titleOfNobility',
                       'Gods',
                       'creator',
                       'NameOfThePerson',
                       'NameOfSmallGeographicUnitLyingWithinAnotherGeographicUnit',
                       'academicDegree',
                       'periodOfActivity',
                       'Company',
                       'GroupOfPersons',
                       'fieldOfActivity',
                       'celebratedPerson',
                       'accreditedComposer',
                       'otherPlace',
                       'hierarchicalSuperiorOfTheCorporateBody',
                       'occasionOfTheSubjectHeading',
                       'variantNameForThePerson',
                       'associatedPlace',
                       'contributingFamily',
                       'poet',
                       'FictivePlace',
                       'organizerOrHost',
                       'variantNameForTheSubjectHeading',
                       'publication',
                       'playedInstrument',
                       'precedingPlaceOrGeographicName',
                       'bookdesigner',
                       'translator',
                       'MeansOfTransportWithIndividual_name',
                       'keyOfTheWork',
                       'Person',
                       'affiliation',
                       'FullerFormOfNameOfThePerson',
                       'inventor',
                       'musician',
                       'painter',
                       'formOfWorkAndExpression',
                       'professionOrOccupation',
                       'relatedPerson',
                       'functionOrRoleAsLiteral',
                       'marc21equivalent',
                       'Country',
                       'mediumOfPerformance',
                       'titleOfNobilityAsLiteral',
                       'oldAuthorityNumber',
                       'relatedDdcWithDegreeOfDeterminacy1',
                       'thematicIndexNumericDesignationOfMusicalWork',
                       'variantNameForTheConferenceOrEvent',
                       'MemberState',
                       'OrganOfCorporateBody',
                       'Pseudonym',
                       'founder',
                       'placeOfDeath',
                       'contributingPlaceOrGeographicName',
                       'ProductNameOrBrandName',
                       'artist',
                       'exhibitor',
                       'predecessor',
                       'placeOfActivity',
                       'UndifferentiatedPerson',
                       'geographicAreaCode',
                       'abbreviatedNameForTheCorporateBody',
                       'broaderTermInstantial',
                       'preferredNameForTheSubjectHeading',
                       'precedingCorporateBody',
                       'associatedDate',
                       'author',
                       'cartographer',
                       'broaderTermGeneric',
                       'EthnographicName',
                       'citedAuthor',
                       'functionOrRole',
                       'narrowerTermInstantial',
                       'RealNameOfThePerson',
                       'abbreviatedNameForThePlaceOrGeographicName',
                       'temporaryNameOfThePlaceOrGeographicName',
                       'opusNumericDesignationOfMusicalWork',
                       'variantNameForThePlaceOrGeographicName',
                       'collector',
                       'dedicatee',
                       'initiator',
                       'printer',
                       'AuthorityResource',
                       'SeriesOfConferenceOrEvent',
                       'contributingPerson',
                       'scriptorium',
                       'prefix',
                       'MusicalWork',
                       'NaturalGeographicUnit',
                       'HistoricSingleEventOrEra',
                       'celebratedTopic',
                       'firstArtist',
                       'pseudonym',
                       'sculptor',
                       'successor',
                       'succeedingConferenceOrEvent',
                       'corporateBodyIsMember',
                       'precedingConferenceOrEvent',
                       'homepage',
                       'spatialAreaOfActivity',
                       'fictitiousAuthor',
                       'instrument',
                       'narrowerTermPartitive',
                       'copist',
                       'surname',
                       'relatedDdcWithDegreeOfDeterminacy3',
                       'librettist',
                       'LaterNameOfThePerson',
                       'WayBorderOrLine',
                       'professionalRelationship',
                       'PseudonymNameOfThePerson',
                       'narrator',
                       'succeedingPlaceOrGeographicName',
                       'member',
                       'CollectiveManuscript',
                       'gender',
                       'realIdentity',
                       'relatedSubjectHeading',
                       'citedComposer',
                       'illustratorOrIlluminator',
                       'affiliationAsLiteral',
                       'abbreviatedNameForTheConferenceOrEvent',
                       'doubtfulAuthor',
                       'westernmostLongitude',
                       'forename',
                       'contributingCorporateBody',
                       'dateOfDeath',
                       'placeOfConferenceOrEvent',
                       'restorer',
                       'ExtraterrestrialTerritory',
                       'NomenclatureInBiologyOrChemistry',
                       'Manuscript',
                       'startingOrFinalPointOfADistance',
                       'personalName',
                       'endOfPeriod',
                       'relatedDdcWithDegreeOfDeterminacy4',
                       'northernmostLatitude',
                       'relatedCorporateBody',
                       'DifferentiatedPerson',
                       'Language',
                       'lithographer',
                       'placeOfBusiness',
                       'celebratedCorporateBody',
                       'characteristicPlace',
                       'dateOfProduction',
                       'serialNumericDesignationOfMusicalWork',
                       'FictiveTerm',
                       'easternmostLongitude',
                       'benefactor',
                       'doubtfulArtist',
                       'dateOfTermination',
                       'succeedingWork',
                       'southernmostLatitude',
                       'EarlierNameOfThePerson',
                       'firstAuthor',
                       'correspondent',
                       'occasion',
                       'keyOfTheVersion',
                       'occasionOfTheWork',
                       'languageCode',
                       'VersionOfAMusicalWork',
                       'PreferredNameOfThePerson',
                       'succeedingCorporateBody',
                       'BuildingOrMemorial',
                       'ReligiousAdministrativeUnit',
                       'Collection',
                       'narrowerTermGeneral',
                       'accordingWork',
                       'temporaryNameOfTheConferenceOrEvent',
                       'bookbinder',
                       'accreditedArtist',
                       'literarySource',
                       'FictiveCorporateBody',
                       'placeOfDiscovery',
                       'curator',
                       'counting',
                       'nameAddition',
                       'ReligiousTerritory',
                       'variantNameEntityForThePerson',
                       'preferredNameForTheWork',
                       'abbreviatedNameForTheWork',
                       'familialRelationship',
                       'succeedingSubjectHeading',
                       'Family',
                       'dateOfBirthAndDeath',
                       'CharactersOrMorphemes',
                       'CollectivePseudonym',
                       'udkCode',
                       'preferredNameForThePerson',
                       'hierarchicalSuperior',
                       'ConferenceOrEvent',
                       'fieldOfStudy',
                       'citedArtist',
                       'ProjectOrProgram',
                       'LiteraryOrLegendaryCharacter',
                       'placeOfCustody',
                       'beginningOfPeriod',
                       'preferredNameForTheCorporateBody',
                       'revisor',
                       'subeditor',
                       'buildingOwner',
                       'relatedSubjecHeading',
                       'placeOfDeathAsLiteral',
                       'topic',
                       'placeOrGeographicNameIsMember',
                       'relatedTerm',
                       'dateOfBirth',
                       'dateOfConferenceOrEvent',
                       'photographer',
                       'ReligiousCorporateBody',
                       'preferredName',
                       'AdministrativeUnit',
                       'writerOfAddedCommentary',
                       'director',
                       'epithetGenericNameTitleOrTerritory',
                       'annotator',
                       'SubjectHeading',
                       'directorOfPhotography',
                       'firstComposer',
                       'hierarchicalSuperiorOfTheConferenceOrEvent',
                       'editor',
                       'etcher',
                       'relatedPlaceOrGeographicName',
                       'addition',
                       'professionOrOccupationAsLiteral',
                       'preferredNameForTheConferenceOrEvent',
                       'RoyalOrMemberOfARoyalHouse',
                       'Expression',
                       'gndIdentifier',
                       'doubtfulComposer',
                       'engraver',
                       'compiler',
                       'complexSeeReferenceSubject',
                       'variantNameForTheCorporateBody',
                       'ProvenanceCharacteristic',
                       'variantNameForTheFamily',
                       'PlaceOrGeographicName',
                       'conferrer',
                       'contributinFamily',
                       'relatedWork',
                       'dateOfEstablishment',
                       'screenwriter',
                       'variantName',
                       'broaderTermGeneral',
                       'dateOfPublication',
                       'dateOfDiscovery',
                       'CorporateBody',
                       'celebratedFamily',
                       'dateOfEstablishmentAndTermination',
                       'singer',
                       'manufacturer',
                       'MeansOfTransportWithIndividualName',
                       'TerritorialCorporateBodyOrAdministrativeUnit',
                       'language',
                       'VariantNameOfThePerson',
                       'broaderTermPartitive',
                       'temporaryName',
                       'Spirits',
                       'variantNameForTheWork',
                       'Fictive_term',
                       'placeOfBirth',
                       'placeOfExile',
                       'instrumentalist',
                       'formerOwner'}

geoAreaCodes = {'XA-CH-AG': 'Aargau',
                'XC-EG': 'Ägypten',
                'XC-GQ': 'Äquatorialguinea',
                'XC-ET': 'Äthiopien', 
                'XB-AF': 'Afghanistan',
                'XC': 'Afrika',
                'XA-AX': 'Ålandinseln',
                'XA-AL': 'Albanien', 
                'XC-DZ': 'Algerien',
                'XD': 'Amerika',
                'XM-UM': 'Amerikanische Überseeinseln', 
                'XD-AS': 'Amerikanisch-Samoa',
                'XA-AD': 'Andorra',
                'XC-AO': 'Angola',
                'XD-AI': 'Anguilla', 
                'XI-AQ': 'Antarktika',
                'XI': 'Antarktis',
                'XD-AG': 'Antigua und Barbuda', 
                'XA-CH-AR': 'Appenzell Ausserrhoden',
                'XA-CH-AI': 'Appenzell Innerrhoden', 
                'XD-AR': 'Argentinien',
                'XH': 'Arktis',
                'XB-AM': 'Armenien',
                'XD-AW': 'Aruba', 
                'XB-AZ': 'Aserbaidschan',
                'XB': 'Asien',
                'XK': 'Atlantischer Ozean',
                'XE-AU': 'Australien',
                'XE': 'Australien, Ozeanien',
                'XA-DE-BW': 'Baden-Württemberg', 
                'XD-BS': 'Bahamas',
                'XB-BH': 'Bahrain',
                'XB-BD': 'Bangladesch',
                'XD-BB': 'Barbados', 
                'XA-CH-BS': 'Basel',
                'XA-CH-BL': 'Basel-Landschaft',
                'XA-DE-BY': 'Bayern', 
                'XA-BE': 'Belgien',
                'XD-BZ': 'Belize',
                'XC-BJ': 'Benin',
                'XA-DE-BE': 'Berlin', 
                'XD-BM': 'Bermudainseln',
                'XB-BT': 'Bhutan',
                'XB-MM': 'Birma',
                'XD-BO': 'Bolivien', 
                'XD-BQ': 'Bonaire, Sint Eustatius, Saba (Insel)',
                'XA-BA': 'Bosnien-Herzegowina', 
                'XC-BW': 'Botswana',
                'XK-BV': 'Bouvetinsel',
                'XA-DE-BB': 'Brandenburg', 
                'XD-BR': 'Brasilien',
                'XA-DE-HB': 'Bremen',
                'XI-BQAQ': 'Britisches Antarktis-Territorium', 
                'XL-IO': 'Britisches Territorium im Indischen Ozean',
                'XB-BN': 'Brunei',
                'XA-BG': 'Bulgarien', 
                'XA-AT-1': 'Burgenland',
                'XC-BF': 'Burkina Faso',
                'XC-BI': 'Burundi', 
                'XD-KY': 'Cayman Islands',
                'XD-CL': 'Chile',
                'XB-CN': 'China', 
                'XE-CX': 'Christmas Island (Australien)',
                'XE-CK': 'Cookinseln',
                'XD-CR': 'Costa Rica', 
                'XD-CW': 'Curaçao',
                'XA-DK': 'Dänemark',
                'XC-DYBJ': 'Dahomey', 
                'XC-CD': 'Demokratische Republik Kongo',
                'XA-DXDE': 'Deutsches Reich',
                'XA-DE': 'Deutschland', 
                'XA-DDDE': 'Deutschland (DDR)',
                'XD-DM': 'Dominica',
                'XD-DO': 'Dominikanische Republik', 
                'XC-DJ': 'Dschibuti',
                'XD-EC': 'Ecuador',
                'XD-SV': 'El Salvador',
                'XC-CI': 'Elfenbeinküste', 
                'XC-ER': 'Eritrea',
                'XA-EE': 'Estland',
                'XA': 'Europa',
                'XK-FO': 'Färöer', 
                'XK-FK': 'Falklandinseln',
                'XE-FJ': 'Fidschi',
                'XA-FI': 'Finnland', 
                'XA-YUCS': 'Föderative Republik Jugoslawien; Jugoslawien',
                'XA-FR': 'Frankreich', 
                'XL-TF': 'Französische Südgebiete',
                'XC-AIDJ': 'Französisches Afar- und Issa-Territorium', 
                'XD-GF': 'Französisch-Guayana',
                'XE-PF': 'Französisch-Polynesien',
                'XC-GA': 'Gabun', 
                'XC-GM': 'Gambia',
                'XB-GE': 'Georgien',
                'XC-GH': 'Ghana',
                'XA-GI': 'Gibraltar', 
                'XE-GEHH': 'Gilbertinseln',
                'XA-CH-GR': 'Graubünden',
                'XD-GD': 'Grenada', 
                'XA-GR': 'Griechenland',
                'XK-GL': 'Grönland',
                'XA-GB': 'Großbritannien', 
                'XD-GP': 'Guadeloupe',
                'XE-GU': 'Guam',
                'XD-GT': 'Guatemala',
                'XA-GG': 'Guernsey', 
                'XC-GN': 'Guinea',
                'XC-GW': 'Guinea-Bissau',
                'XD-GY': 'Guyana',
                'XD-HT': 'Haiti', 
                'XA-DE-HH': 'Hamburg',
                'XI-HM': 'Heard und McDonaldinseln',
                'XA-DE-HE': 'Hessen', 
                'XD-HN': 'Honduras',
                'XB-HK': 'Hongkong',
                'XB-IN': 'Indien',
                'XL': 'Indischer Ozean', 
                'XB-ID': 'Indonesien',
                'XB-IQ': 'Irak',
                'XB-IR': 'Iran',
                'XA-IE': 'Irland', 
                'XA-IS': 'Island',
                'XA-IM': 'Isle of Man',
                'XB-IL': 'Israel',
                'XA-IT': 'Italien', 
                'XD-JM': 'Jamaika',
                'XB-JP': 'Japan',
                'XB-YE': 'Jemen', 
                'XB-YDYE': 'Jemen (Demokratische Volksrepublik)',
                'XA-JE': 'Jersey',
                'XB-JO': 'Jordanien', 
                'XD-VG': 'Jungferninseln (Großbritannien)',
                'XD-VI': 'Jungferninseln (USA)', 
                'XA-AT-2': 'Kärnten',
                'XB-KH': 'Kambodscha',
                'XC-CM': 'Kamerun',
                'XD-CA': 'Kanada', 
                'XA-CH-BE': 'Kanton Bern',
                'XA-CH-FR': 'Kanton Freiburg',
                'XA-CH-GE': 'Kanton Genf', 
                'XA-CH-GL': 'Kanton Glarus',
                'XA-CH-JU': 'Kanton Jura',
                'XA-CH-LU': 'Kanton Luzern', 
                'XA-CH-NE': 'Kanton Neuenburg',
                'XA-CH-SG': 'Kanton Sankt Gallen', 
                'XA-CH-SH': 'Kanton Schaffhausen',
                'XA-CH-SZ': 'Kanton Schwyz', 
                'XA-CH-SO': 'Kanton Solothurn',
                'XA-CH-ZH': 'Kanton Zürich',
                'XA-CH-ZG': 'Kanton Zug', 
                'XC-CV': 'Kap Verde',
                'XB-KZ': 'Kasachstan',
                'XB-QA': 'Katar',
                'XC-KE': 'Kenia', 
                'XB-KG': 'Kirgisien',
                'XE-KI': 'Kiribati',
                'XI-NQAQ': 'Königin-Maud-Land', 
                'XE-CC': 'Kokosinseln',
                'XD-CO': 'Kolumbien',
                'XC-KM': 'Komoren',
                'XA-HR': 'Kroatien', 
                'XD-CU': 'Kuba',
                'XB-KW': 'Kuwait',
                'XA-AT-5': 'Land Salzburg',
                'XB-LA': 'Laos', 
                'XC-LS': 'Lesotho',
                'XA-LV': 'Lettland',
                'XB-LB': 'Libanon',
                'XC-LR': 'Liberia', 
                'XC-LY': 'Libyen',
                'XA-LI': 'Liechtenstein',
                'XA-LT': 'Litauen',
                'XA-LU': 'Luxemburg', 
                'XB-MO': 'Macau',
                'XC-MG': 'Madagaskar',
                'XC-MW': 'Malawi',
                'XB-MY': 'Malaysia', 
                'XB-MV': 'Malediven',
                'XC-ML': 'Mali',
                'XA-MT': 'Malta',
                'XC-MA': 'Marokko', 
                'XE-MH': 'Marshallinseln',
                'XD-MQ': 'Martinique',
                'XC-MR': 'Mauretanien', 
                'XC-MU': 'Mauritius',
                'XC-YT': 'Mayotte',
                'XA-DE-MV': 'Mecklenburg-Vorpommern', 
                'XD-MX': 'Mexiko',
                'XM-MIUM': 'Midway Islands',
                'XC-MZ': 'Moçambique',
                'XA-MD': 'Moldawien', 
                'XA-MC': 'Monaco',
                'XB-MN': 'Mongolei',
                'XA-ME': 'Montenegro',
                'XD-MS': 'Montserrat (Insel)', 
                'XC-NA': 'Namibia',
                'XE-NR': 'Nauru',
                'XB-NP': 'Nepal',
                'XE-NC': 'Neukaledonien', 
                'XE-NZ': 'Neuseeland',
                'XD-NI': 'Nicaragua',
                'XA-CH-NW': 'Nidwalden', 
                'XD-ANHH': 'Niederländische Antillen',
                'XA-NL': 'Niederlande',
                'XA-AT-3': 'Niederösterreich', 
                'XA-DE-NI': 'Niedersachsen',
                'XC-NE': 'Niger',
                'XC-NG': 'Nigeria',
                'XM-NU': 'Niue',
                'XE-MP': 'Nördliche Marianen',
                'XB-KP': 'Nordkorea',
                'XA-MK': 'Nordmazedonien', 
                'XA-DE-NW': 'Nordrhein-Westfalen',
                'XE-NF': 'Norfolk-Insel',
                'XA-NO': 'Norwegen', 
                'XA-AT-4': 'Oberösterreich',
                'XC-HVBF': 'Obervolta',
                'XA-CH-OW': 'Obwalden', 
                'XA-AT': 'Österreich',
                'XA-AAAT': 'Österreich (-12.11.1918)#',
                'XB-OM': 'Oman', 
                'XB-TL': 'Osttimor',
                'XB-TPTL': 'Osttimor',
                'XE-PCHH': 'Ozeanien',
                'XB-PK': 'Pakistan', 
                'XE-PW': 'Palauinseln',
                'XD-PA': 'Panama',
                'XD-PZPA': 'Panamakanalzone', 
                'XE-PG': 'Papua-Neuguinea',
                'XD-PY': 'Paraguay',
                'XM': 'Pazifischer Ozean', 
                'XD-PE': 'Peru',
                'XB-PH': 'Philippinen',
                'XM-PN': 'Pitcairn',
                'XA-PL': 'Polen', 
                'XA-PT': 'Portugal',
                'XB-BUMM': 'Provinz Burma',
                'XD-PR': 'Puerto Rico',
                'XC-CG': 'Republik Kongo',
                'XL-RE': 'Réunion',
                'XA-DE-RP': 'Rheinland-Pfalz',
                'XA-RO': 'Rumänien', 
                'XA-RU': 'Russland',
                'XC-RW': 'Ruanda',
                'XA-DE-SL': 'Saarland',
                'XA-DE-SN': 'Sachsen', 
                'XA-DE-ST': 'Sachsen-Anhalt',
                'XD-KN': 'Saint Kitts und Nevis',
                'XD-LC': 'Saint Lucia', 
                'XD-VC': 'Saint Vincent and the Grenadines',
                'XD-BL': 'Saint-Barthélemy (Kleine Antillen)', 
                'XD-MF': 'Saint-Martin (Kleine Antillen, Nord)',
                'XD-PM': 'Saint-Pierre-et-Miquelon', 
                'XE-SB': 'Salomonen',
                'XC-ZM': 'Sambia',
                'XA-SM': 'San Marino',
                'XK-SH': 'Sankt Helena', 
                'XC-ST': 'Sao Tomé und Príncipe',
                'XB-SA': 'Saudi-Arabien',
                'XA-DE-SH': 'Schleswig-Holstein', 
                'XA-SE': 'Schweden',
                'XA-CH': 'Schweiz',
                'XC-SN': 'Senegal',
                'XA-RS': 'Serbien', 
                'XA-CSXX': 'Serbien und Montenegro',
                'XC-SC': 'Seychellen',
                'XC-SL': 'Sierra Leone', 
                'XB-SKIN': 'Sikkim',
                'XC-ZW': 'Simbabwe',
                'XB-SG': 'Singapur',
                'XD-SX': 'Sint Maarten', 
                'XA-SK': 'Slowakei',
                'XA-SI': 'Slowenien',
                'XC-SO': 'Somalia',
                'XA-SUHH': 'Sowjetunion', 
                'XA-ES': 'Spanien',
                'XB-LK': 'Sri Lanka',
                'XE-FM': 'Staat Mikronesien', 
                'XC-SS': 'Staat Südsudan',
                'XA-AT-6': 'Steiermark',
                'XC-SD': 'Sudan',
                'XC-ZA': 'Südafrika', 
                'XK-GS': 'Südgeorgien und Südliche Sandwichinseln',
                'XB-KR': 'Südkorea', 
                'XC-RHZW': 'Südrhodesien',
                'XB-VDVN': 'Südvietnam',
                'XD-SR': 'Surinam', 
                'XK-SJ': 'Svalbard und Jan Mayen',
                'XC-SZ': 'Swasiland',
                'XB-SY': 'Syrien', 
                'XB-TJ': 'Tadschikistan',
                'XB-TW': 'Taiwan',
                'XC-TZ': 'Tansania', 
                'XI-FQHH': 'Terres Australes et Antarctiques Françaises',
                'XA-CH-TI': 'Tessin', 
                'XB-TH': 'Thailand',
                'XA-DE-TH': 'Thüringen',
                'XA-CH-TG': 'Thurgau',
                'XB-CN-54': 'Tibet', 
                'XA-AT-7': 'Tirol',
                'XC-TG': 'Togo',
                'XE-TK': 'Tokelau',
                'XE-TO': 'Tonga', 
                'XA-IT-32': 'Trentino-Südtirol',
                'XD-TT': 'Trinidad und Tobago',
                'XC-TD': 'Tschad', 
                'XA-CZ': 'Tschechische Republik',
                'XA-CSHH': 'Tschechoslowakei',
                'XB-TR': 'Türkei', 
                'XC-TN': 'Tunesien',
                'XB-TM': 'Turkmenistan',
                'XD-TC': 'Turks- und Caicosinseln', 
                'XE-TV': 'Tuvalu',
                'XC-UG': 'Uganda',
                'XA-UA': 'Ukraine',
                'XA-HU': 'Ungarn', 
                'XA-CH-UR': 'Uri',
                'XD-UY': 'Uruguay',
                'XD-US': 'USA',
                'XB-UZ': 'Usbekistan', 
                'XE-VU': 'Vanuatu',
                'XE-NHVU': 'Vanuatu (Neue Hebriden)',
                'XA-VA': 'Vatikanstadt', 
                'XD-VE': 'Venezuela',
                'XB-AE': 'Vereinigte Arabische Emirate',
                'XB-VN': 'Vietnam', 
                'XA-AT-8': 'Vorarlberg',
                'XA-CH-VD': 'Waadt',
                'XM-WKUM': 'Wake Island', 
                'XA-CH-VS': 'Wallis',
                'XE-WF': 'Wallis und Futuna',
                'XA-BY': 'Weißrussland', 
                'XC-EH': 'Westsahara',
                'XE-WS': 'Westsamoa',
                'XA-AT-9': 'Wien',
                'XC-ZRCD': 'Zaire', 
                'XC-CF': 'Zentralafrikanische Republik',
                'XA-CY': 'Zypern', 
                'XX': 'Arabische Staaten, Araber (Repräsentanten des arabischen Sprach- und Kulturkreises, der nicht an einen bestimmten Staat gebunden ist)', 
                'XN': 'Extraterrestrika',
                'XZ': 'Fiktive Geografika', 
                'XQ': 'Gesamte Welt, Übrige Welt',
                'XP': 'internationale Körperschaften der Jüdischer Kulturkreis (Repräsentanten des jüdischen Kulturkreises,', 
                'XY': 'nicht an den Staat Israel gebunden ist)',
                'XW': 'Palästinenser in Geschichte und Gegenwart', 
                'ZZ': 'Land unbekannt',
                'XR': 'Alter Orient',
                'XU': 'Byzantinisches Reich', 
                'XS': 'Griechenland (Altertum)',
                'XV': 'Osmanisches Reich',
                'XT': 'Römisches Reich', 
                'XM-PUUM': 'Amerikanisches Territorium im Pazifik (-1986)',
                'XE-CTKI': 'Canton und Enderbury (-1984)', 
                'XA-FXFR': 'Frankreich, Europäisches (1993-1997)',
                'XM-JTUM': 'Johnston-Insel (-1986)', 
                'XB-NTHH': 'Neutrale Zone (-1993)',
                'XA-BYAA': 'Weißrussland (-1992)'}

relationBibTypeList = {'abr': 'Abridger',
                       'acp': 'Art copyist',
                       'act': 'Actor',
                       'adi': 'Art director',
                       'adp': 'Adapter',
                       'aft': 'Author of afterword, colophon, etc.',
                       'anl': 'Analyst',
                       'anm': 'Animator',
                       'ann': 'Annotator',
                       'ant': 'Bibliographic antecedent',
                       'ape': 'Appellee',
                       'apl': 'Appellant',
                       'app': 'Applicant',
                       'aqt': 'Author in quotations or text abstracts',
                       'arc': 'Architect',
                       'ard': 'Artistic director',
                       'arr': 'Arranger',
                       'art': 'Artist',
                       'asg': 'Assignee',
                       'asn': 'Associated name',
                       'ato': 'Autographer',
                       'att': 'Attributed name',
                       'auc': 'Auctioneer',
                       'aud': 'Author of dialog',
                       'aui': 'Author of introduction, etc.',
                       'aus': 'Screenwriter',
                       'aut': 'Author',
                       'bdd': 'Binding designer',
                       'bjd': 'Bookjacket designer',
                       'bkd': 'Book designer',
                       'bkp': 'Book producer',
                       'blw': 'Blurb writer',
                       'bnd': 'Binder',
                       'bpd': 'Bookplate designer',
                       'brd': 'Broadcaster',
                       'brl': 'Braille embosser',
                       'bsl': 'Bookseller',
                       'cas': 'Caster',
                       'ccp': 'Conceptor',
                       'chr': 'Choreographer',
                       '-clb': 'Collaborator',
                       'cli': 'Client',
                       'cll': 'Calligrapher',
                       'clr': 'Colorist',
                       'clt': 'Collotyper',
                       'cmm': 'Commentator',
                       'cmp': 'Composer',
                       'cmt': 'Compositor',
                       'cnd': 'Conductor',
                       'cng': 'Cinematographer',
                       'cns': 'Censor',
                       'coe': 'Contestant-appellee',
                       'col': 'Collector',
                       'com': 'Compiler',
                       'con': 'Conservator',
                       'cor': 'Collection registrar',
                       'cos': 'Contestant',
                       'cot': 'Contestant-appellant',
                       'cou': 'Court governed',
                       'cov': 'Cover designer',
                       'cpc': 'Copyright claimant',
                       'cpe': 'Complainant-appellee',
                       'cph': 'Copyright holder',
                       'cpl': 'Complainant',
                       'cpt': 'Complainant-appellant',
                       'cre': 'Creator',
                       'crp': 'Correspondent',
                       'crr': 'Corrector',
                       'crt': 'Court reporter',
                       'csl': 'Consultant',
                       'csp': 'Consultant to a project',
                       'cst': 'Costume designer',
                       'ctb': 'Contributor',
                       'cte': 'Contestee-appellee',
                       'ctg': 'Cartographer',
                       'ctr': 'Contractor',
                       'cts': 'Contestee',
                       'ctt': 'Contestee-appellant',
                       'cur': 'Curator',
                       'cwt': 'Commentator for written text',
                       'dbp': 'Distribution place',
                       'dfd': 'Defendant',
                       'dfe': 'Defendant-appellee',
                       'dft': 'Defendant-appellant',
                       'dgg': 'Degree granting institution',
                       'dgs': 'Degree supervisor',
                       'dis': 'Dissertant',
                       'dln': 'Delineator',
                       'dnc': 'Dancer',
                       'dnr': 'Donor',
                       'dpc': 'Depicted',
                       'dpt': 'Depositor',
                       'drm': 'Draftsman',
                       'drt': 'Director',
                       'dsr': 'Designer',
                       'dst': 'Distributor',
                       'dtc': 'Data contributor',
                       'dte': 'Dedicatee',
                       'dtm': 'Data manager',
                       'dto': 'Dedicator',
                       'dub': 'Dubious author',
                       'edc': 'Editor of compilation',
                       'edm': 'Editor of moving image work',
                       'edt': 'Editor',
                       'egr': 'Engraver',
                       'elg': 'Electrician',
                       'elt': 'Electrotyper',
                       'eng': 'Engineer',
                       'enj': 'Enacting jurisdiction',
                       'etr': 'Etcher',
                       'evp': 'Event place',
                       'exp': 'Expert',
                       'fac': 'Facsimilist',
                       'fds': 'Film distributor',
                       'fld': 'Field director',
                       'flm': 'Film editor',
                       'fmd': 'Film director',
                       'fmk': 'Filmmaker',
                       'fmo': 'Former owner',
                       'fmp': 'Film producer',
                       'fnd': 'Funder',
                       'fpy': 'First party',
                       'frg': 'Forger',
                       'gis': 'Geographic information specialist',
                       '-grt': 'Graphic technician',
                       'his': 'Host institution',
                       'hnr': 'Honoree',
                       'hst': 'Host',
                       'ill': 'Illustrator',
                       'ilu': 'Illuminator',
                       'ins': 'Inscriber',
                       'inv': 'Inventor',
                       'isb': 'Issuing body',
                       'itr': 'Instrumentalist',
                       'ive': 'Interviewee',
                       'ivr': 'Interviewer',
                       'jud': 'Judge',
                       'jug': 'Jurisdiction governed',
                       'lbr': 'Laboratory',
                       'lbt': 'Librettist',
                       'ldr': 'Laboratory director',
                       'led': 'Lead',
                       'lee': 'Libelee-appellee',
                       'lel': 'Libelee',
                       'len': 'Lender',
                       'let': 'Libelee-appellant',
                       'lgd': 'Lighting designer',
                       'lie': 'Libelant-appellee',
                       'lil': 'Libelant',
                       'lit': 'Libelant-appellant',
                       'lsa': 'Landscape architect',
                       'lse': 'Licensee',
                       'lso': 'Licensor',
                       'ltg': 'Lithographer',
                       'lyr': 'Lyricist',
                       'mcp': 'Music copyist',
                       'mdc': 'Metadata contact',
                       'med': 'Medium',
                       'mfp': 'Manufacture place',
                       'mfr': 'Manufacturer',
                       'mod': 'Moderator',
                       'mon': 'Monitor',
                       'mrb': 'Marbler',
                       'mrk': 'Markup editor',
                       'msd': 'Musical director',
                       'mte': 'Metal-engraver',
                       'mtk': 'Minute taker',
                       'mus': 'Musician',
                       'nrt': 'Narrator',
                       'opn': 'Opponent',
                       'org': 'Originator',
                       'orm': 'Organizer',
                       'osp': 'Onscreen presenter',
                       'oth': 'Other',
                       'own': 'Owner',
                       'pan': 'Panelist',
                       'pat': 'Patron',
                       'pbd': 'Publishing director',
                       'pbl': 'Publisher',
                       'pdr': 'Project director',
                       'pfr': 'Proofreader',
                       'pht': 'Photographer',
                       'plt': 'Platemaker',
                       'pma': 'Permitting agency',
                       'pmn': 'Production manager',
                       'pop': 'Printer of plates',
                       'ppm': 'Papermaker',
                       'ppt': 'Puppeteer',
                       'pra': 'Praeses',
                       'prc': 'Process contact',
                       'prd': 'Production personnel',
                       'pre': 'Presenter',
                       'prf': 'Performer',
                       'prg': 'Programmer',
                       'prm': 'Printmaker',
                       'prn': 'Production company',
                       'pro': 'Producer',
                       'prp': 'Production place',
                       'prs': 'Production designer',
                       'prt': 'Printer',
                       'prv': 'Provider',
                       'pta': 'Patent applicant',
                       'pte': 'Plaintiff-appellee',
                       'ptf': 'Plaintiff',
                       'pth': 'Patent holder',
                       'ptt': 'Plaintiff-appellant',
                       'pup': 'Publication place',
                       'rbr': 'Rubricator',
                       'rcd': 'Recordist',
                       'rce': 'Recording engineer',
                       'rcp': 'Addressee',
                       'rdd': 'Radio director',
                       'red': 'Redaktor',
                       'ren': 'Renderer',
                       'res': 'Researcher',
                       'rev': 'Reviewer',
                       'rpc': 'Radio producer',
                       'rps': 'Repository',
                       'rpt': 'Reporter',
                       'rpy': 'Responsible party',
                       'rse': 'Respondent-appellee',
                       'rsg': 'Restager',
                       'rsp': 'Respondent',
                       'rsr': 'Restorationist',
                       'rst': 'Respondent-appellant',
                       'rth': 'Research team head',
                       'rtm': 'Research team member',
                       'sad': 'Scientific advisor',
                       'sce': 'Scenarist',
                       'scl': 'Sculptor',
                       'scr': 'Scribe',
                       'sds': 'Sound designer',
                       'sec': 'Secretary',
                       'sgd': 'Stage director',
                       'sgn': 'Signer',
                       'sht': 'Supporting host',
                       'sll': 'Seller',
                       'sng': 'Singer',
                       'spk': 'Speaker',
                       'spn': 'Sponsor',
                       'spy': 'Second party',
                       'srv': 'Surveyor',
                       'std': 'Set designer',
                       'stg': 'Setting',
                       'stl': 'Storyteller',
                       'stm': 'Stage manager',
                       'stn': 'Standards body',
                       'str': 'Stereotyper',
                       'tcd': 'Technical director',
                       'tch': 'Teacher',
                       'ths': 'Thesis advisor',
                       'tld': 'Television director',
                       'tlp': 'Television producer',
                       'trc': 'Transcriber',
                       'trl': 'Translator',
                       'tyd': 'Type designer',
                       'tyg': 'Typographer',
                       'uvp': 'University place',
                       'vac': 'Voice actor',
                       'vdg': 'Videographer',
                       '-voc': 'Vocalist',
                       'wac': 'Writer of added commentary',
                       'wal': 'Writer of added lyrics',
                       'wam': 'Writer of accompanying material',
                       'wat': 'Writer of added text',
                       'wdc': 'Woodcutter',
                       'wde': 'Wood engraver',
                       'win': 'Writer of introduction',
                       'wit': 'Witness',
                       'wpr': 'Writer of preface',
                       'wst': 'Writer of supplementary textual content'}